#!/bin/bash

# Custom functions

cs() {
  cd "$1" && ls -la
}

ofv() {
  sudo openfortivpn -c "/etc/openfortivpn/${1}"
}

precmd() {
  echo -ne "\033]0;${PWD/#$HOME/~}\007"
}

prepath() {
  for dir in "$@"; do
    case ":$PATH:" in
      *:"$dir":*) ;;
      *) PATH="$dir:$PATH" ;;
    esac
  done
  export PATH
}

ssha() {
  ssh-add "$HOME/.ssh/${1}"
}

udd() {
  udisks --detach "/dev/${1}"
}
