#!/bin/bash

# Custom functions

function cs() {
  cd "$1" && ls -la
}

function ofv() {
  sudo openfortivpn -c "/etc/openfortivpn/${1}"
}

function precmd() {
  echo -ne "\033]0;${PWD/#$HOME/~}\007"
}

function ssha() {
  ssh-add "$HOME/.ssh/${1}"
}

function udd() {
  udisks --detach "/dev/${1}"
}
